import type { FRAXQuestion } from '@/lib/types/frax-quiz'

export const FRAX_QUESTIONS: FRAXQuestion[] = [
  {
    id: 'age',
    number: 1,
    question: 'Ваш возраст',
    description: 'Введите ваш возраст в годах',
    type: 'number',
    required: true,
  },
  {
    id: 'sex',
    number: 2,
    question: 'Ваш пол',
    description: 'Выберите ваш пол',
    type: 'select',
    options: [
      { value: 'female', label: 'Женский' },
      { value: 'male', label: 'Мужской' },
    ],
    required: true,
  },
  {
    id: 'previous_fracture',
    number: 3,
    question: 'Был ли у вас перелом после 40 лет?',
    description: 'Перелом кости, произошедший после 40 лет, в результате минимальной травмы (например, падение с высоты собственного роста)',
    type: 'yes_no',
    required: true,
  },
  {
    id: 'parent_hip_fracture',
    number: 4,
    question: 'Был ли перелом шейки бедра у ваших родителей?',
    description: 'Перелом шейки бедра у матери или отца',
    type: 'yes_no',
    required: true,
  },
  {
    id: 'current_smoking',
    number: 5,
    question: 'Курите ли вы в настоящее время?',
    description: 'Регулярное курение сигарет, сигар или других табачных изделий',
    type: 'yes_no',
    required: true,
  },
  {
    id: 'glucocorticoids',
    number: 6,
    question: 'Принимаете ли вы глюкокортикоиды?',
    description: 'Приём преднизолона или эквивалента в дозе ≥5 мг/день в течение ≥3 месяцев',
    type: 'yes_no',
    required: true,
  },
  {
    id: 'rheumatoid_arthritis',
    number: 7,
    question: 'Есть ли у вас ревматоидный артрит?',
    description: 'Диагностированный ревматоидный артрит',
    type: 'yes_no',
    required: true,
  },
  {
    id: 'secondary_osteoporosis',
    number: 8,
    question: 'Есть ли у вас вторичный остеопороз?',
    description: 'Остеопороз, вызванный другими заболеваниями (например, диабет 1 типа, недоедание, хронические заболевания печени)',
    type: 'yes_no',
    required: true,
  },
  {
    id: 'alcohol',
    number: 9,
    question: 'Употребляете ли вы алкоголь в количестве ≥3 единиц в день?',
    description: '3 или более единиц алкоголя в день (1 единица = 10 мл чистого спирта)',
    type: 'yes_no',
    required: true,
  },
  {
    id: 'bmd',
    number: 10,
    question: 'Плотность костной ткани (BMD) шейки бедра (опционально)',
    description: 'Если у вас есть результаты денситометрии, введите значение T-score. Если нет — оставьте пустым.',
    type: 'number',
    required: false,
  },
]

